name: BossQuests
version: 2.1
description: Quests module for Boss
author: Browsit
website: https://github.com/Browsit/BossQuestsModule

main: org.browsit.BossQuestsModule
depend: [Boss, Quests]